"""
Analytics API Router
Provides multi-axis price history, quantitative indicators, trading signals, and summary metrics.
"""

from fastapi import APIRouter, Query, HTTPException
from typing import List, Dict, Any, Optional
from backend.database import db_manager
from backend.schemas import PriceTrendsResponse, PricePoint, TradingSignal

router = APIRouter(prefix="/api/v1/analytics", tags=["Analytics"])


@router.get("/price-trends", response_model=PriceTrendsResponse)
def get_price_trends(
    symbol: str = Query("BTC", description="Cryptocurrency symbol, e.g. BTC, ETH"),
    days: int = Query(30, description="Number of historical days to fetch")
):
    """
    Returns time series OHLCV candle data alongside technical indicators (SMA, EMA, RSI, MACD).
    """
    sym = symbol.strip().upper()
    query = """
    SELECT 
        c.name AS crypto_name,
        f.timestamp,
        f.date_key,
        f.open_price AS open,
        f.high_price AS high,
        f.low_price AS low,
        f.close_price AS close,
        f.volume,
        f.sma_7,
        f.sma_25,
        f.ema_12,
        f.ema_26,
        f.rsi_14,
        f.macd,
        f.macd_signal
    FROM fact_price_history f
    JOIN dim_cryptos c ON f.crypto_key = c.crypto_key
    WHERE c.symbol = ?
    ORDER BY f.timestamp ASC
    LIMIT ?;
    """
    rows = db_manager.query_warehouse(query, (sym, days))
    if not rows:
        # Check if symbol exists
        sym_check = db_manager.query_warehouse("SELECT name FROM dim_cryptos WHERE symbol = ?", (sym,))
        crypto_name = sym_check[0]["name"] if sym_check else sym
        return PriceTrendsResponse(symbol=sym, name=crypto_name, count=0, data=[])

    crypto_name = rows[0]["crypto_name"]
    price_points = []
    for r in rows:
        price_points.append(PricePoint(
            timestamp=r["timestamp"],
            date_key=r["date_key"],
            open=round(r["open"], 4),
            high=round(r["high"], 4),
            low=round(r["low"], 4),
            close=round(r["close"], 4),
            volume=round(r["volume"], 2),
            sma_7=r["sma_7"],
            sma_25=r["sma_25"],
            ema_12=r["ema_12"],
            ema_26=r["ema_26"],
            rsi_14=r["rsi_14"],
            macd=r["macd"],
            macd_signal=r["macd_signal"]
        ))

    return PriceTrendsResponse(
        symbol=sym,
        name=crypto_name,
        count=len(price_points),
        data=price_points
    )


@router.get("/signals", response_model=List[TradingSignal])
def get_trading_signals(
    symbol: Optional[str] = Query(None, description="Optional symbol filter"),
    limit: int = Query(20, description="Max signals to return")
):
    """
    Retrieves the latest quantitative trading signals generated by the pipeline.
    """
    if symbol:
        query = """
        SELECT * FROM v_latest_trading_signals
        WHERE symbol = ?
        ORDER BY generated_at DESC LIMIT ?;
        """
        rows = db_manager.query_warehouse(query, (symbol.strip().upper(), limit))
    else:
        query = """
        SELECT * FROM v_latest_trading_signals
        ORDER BY generated_at DESC LIMIT ?;
        """
        rows = db_manager.query_warehouse(query, (limit,))

    signals = []
    for r in rows:
        signals.append(TradingSignal(
            signal_id=r["signal_id"],
            symbol=r["symbol"],
            crypto_name=r["crypto_name"],
            category=r["category"] or "Crypto Asset",
            signal_name=r["signal_name"],
            risk_level=r["risk_level"],
            strategy_name=r["strategy_name"],
            trigger_price=round(float(r["trigger_price"]), 4),
            confidence_score=round(float(r["confidence_score"]), 2),
            technical_reason=r["technical_reason"],
            sentiment_weight=round(float(r.get("sentiment_weight") or 0.0), 2),
            generated_at=r["generated_at"]
        ))

    return signals


@router.get("/summary")
def get_market_summary() -> Dict[str, Any]:
    """
    Computes aggregated market statistics: Signal distribution, sentiment index, top movers.
    """
    # 1. Signal breakdown
    sig_rows = db_manager.query_warehouse("""
        SELECT signal_name, COUNT(*) as count
        FROM (
            SELECT signal_name, ROW_NUMBER() OVER(PARTITION BY crypto_key ORDER BY timestamp DESC) as rn
            FROM fact_signals
        )
        WHERE rn = 1
        GROUP BY signal_name;
    """)
    distribution = {r["signal_name"]: r["count"] for r in sig_rows}

    # 2. Average sentiment
    sent_rows = db_manager.query_warehouse("""
        SELECT AVG(sentiment_score) as avg_score, COUNT(*) as total_news
        FROM fact_news_sentiment;
    """)
    avg_score = float(sent_rows[0]["avg_score"] or 0.0) if sent_rows else 0.0
    total_news = sent_rows[0]["total_news"] if sent_rows else 0

    # 3. Overall Market Mood Index (0 to 100)
    sentiment_index = int(50.0 + (avg_score * 40.0))

    return {
        "signal_distribution": distribution,
        "average_sentiment_score": round(avg_score, 3),
        "market_mood_index": sentiment_index,
        "market_mood_label": "EXTREME_GREED" if sentiment_index > 75 else "GREED" if sentiment_index > 55 else "NEUTRAL" if sentiment_index >= 45 else "FEAR",
        "total_news_analyzed": total_news
    }
